{% set name = "tensorflow-metadata" %}
{% set version = "1.13.1" %}
# This is the recipe for tensorflow-metadata
package:
   name: {{ name }}
   version: {{ version }}

source:
  git_url: https://github.com/tensorflow/metadata.git
  git_rev: v{{ version }}
  patches:
    - 0002-Update-zlib-to-1.2.13.patch 
  
build:
  number: 1
  string: pyh{{ PKG_HASH }}_pb{{ protobuf | replace(".*", "")}}_{{ PKG_BUILDNUM }}
  noarch: python

requirements:
  build:
    - {{ compiler('c') }}       #[ppc_arch != 'p10']
    - {{ compiler('cxx') }}     #[ppc_arch != 'p10']
  host:
    - bazel {{ bazel }}
    - python
  run:
    - python 
    - absl-py {{ absl_py }}
    - googleapis-common-protos {{ googleapis_common_protos }}
    - protobuf {{ protobuf }}

test:
  imports:
    - tensorflow_metadata

about:
  home: https://github.com/tensorflow/metadata.git
  license: Apache License 2.0
  license_file: {{ SRC_DIR }}/LICENSE
  license_family: APACHE
  summary: "Utilities for passing TensorFlow-related metadata between tools"
  description: |
      TensorFlow Metadata provides standard representations for metadata
      that are useful when training machine learning models with TensorFlow.
      The metadata serialization formats include- 
          - A schema describing tabular data (e.g., tf.Examples).
          - A collection of summary statistics over such datasets.
          - A problem statement quantifying the objectives of a model.
      The metadata may be produced by hand or automatically during input data analysis,
      and may be consumed for data validation, exploration, and transformation. 
  dev_url: https://github.com/tensorflow/metadata.git
  doc_url: https://github.com/tensorflow/metadata.git  

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
